### PR TITLE
Feat - JSON Glossary

### PR DESCRIPTION
**Pull request by lucas-tortora**
# Description of change

* Added JSON Based glossary
* Added react tooltip package
* Added GlossaryTooltip component

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Wiki was built locally.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested the wiki locally and tested that all external links work

### CODE REVIEW

**Comment by lucas-tortora** [comment]
@Dr-Electron, I think I sorted out the nuisances we discussed last week.  
@jlvandenhout, if you have some time, it'd be great to get your opinion on this.

**Review by aleksei-korolev — APPROVED** [review]

**Comment by Dr-Electron** [comment]
@lucas-tortora can I ask you to merge the merge conflicts?

**Comment by Dr-Electron** [comment]
Nice. Now the build fails 😅

**Comment by jlvandenhout** [comment]
Just to be sure, we still need a way to add these glossary components to the actual terms in the text during build right? If we want to add them manually, that requires all docs to become MDX, which I'm not sure of if we want that.

**Comment by lucas-tortora** [comment]
> Just to be sure, we still need a way to add these glossary components to the actual terms in the text during build right? If we want to add them manually, that requires all docs to become MDX, which I'm not sure of if we want that.

I think that would be ideal, however, I'm not sure how to actually do that. :(

**Comment by Dr-Electron** [comment]
Wasn't the plan to write a remark plugin for that?

**Comment by lucas-tortora** [comment]
> Wasn't the plan to write a remark plugin for that?

It was, but I have no idea where to start to be honest.

**Pull request closed without merging**
