### PR TITLE
Docs - 870 - Add Tips To Sidebar

### PR DESCRIPTION
**Pull request by lucas-tortora**
# Description of change

Added tips to IOTA and Shimmer develop sidebars

## Links to any relevant issues

patch for #870

## Type of change

- Documentation Enhancement

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work

### CODE REVIEW

**Comment by Dr-Electron** [comment]
Can you add it to the `next` section too? Just for "completeness"

**Comment by Dr-Electron** [comment]
And please rebase that should fix the CI/CD formatting complain

**Review by Dr-Electron — APPROVED** [review]
LGTM I think 😅 . Why is git showing the hornet changes? I mean this should still do the correct thing. Just weird that git does't get it 😅

**Comment by lucas-tortora** [comment]
> LGTM I think sweat_smile . Why is git showing the hornet changes? I mean this should still do the correct thing. Just weird that git does't get it sweat_smile

I think that's from the rebase, though it shouldn't really be there, right?

**Comment by Dr-Electron** [comment]
> > LGTM I think sweat_smile . Why is git showing the hornet changes? I mean this should still do the correct thing. Just weird that git does't get it sweat_smile
> 
> I think that's from the rebase, though it shouldn't really be there, right?

Not really... It also shows me that you are now committer of that commit I created as author. So maybe it would be better to redo it...

**Comment by lucas-tortora** [comment]
Closed in favour of https://github.com/iota-wiki/iota-wiki/pull/877

**Pull request closed without merging**
