### PR TITLE
Add rehype-lodash-template to use template strings

### LINKED ISSUE #879: Add templates for version replacements
**Is your feature request related to a problem? Please describe.**

To minimise the problems with merging different version, we should provide variables that replace certain templates so that merging docs won't be a problem (see examples at the end of this issue)

**Describe the solution you'd like**

We maybe could use [rehype-lodash-template](https://github.com/viktor-yakubiv/rehype-lodash-template) or a similar tool to have a list of templates/variables that in the docs will be replaced with the corresponding strings.

For urls this may also be of help: [rehype-url-inspector](https://github.com/JS-DevTools/rehype-url-inspector) (It could even help with [broken links](https://github.com/iota-wiki/iota-wiki/issues/880))

**Describe alternatives you've considered**

Doing it manually :trollface: 

**Additional context**

In the docs you could for example use `${ENVIRONMENT_URL}/hornet/welcome` which in a Shimmer environment would point to `https://wiki.iota.org/shimmer/hornet/iota.org` (or even better use the config parameters) and in an IOTA environment to `https://wiki.iota.org/hornet/iota.org`

Or another markdown example:
```
In ${NETWORK} you always need a storage deposit
```

where `${NETWORK}` will be replaced with either `IOTA` or `Shimmer`

### PR DESCRIPTION
**Pull request by Dr-Electron**
# Description of change

This should make it possible to use template strings like `${network}` for easier management of different versions of our docs

## Links to any relevant issues

Fixes #879 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by jlvandenhout — APPROVED** [review]

**Comment by Dr-Electron** [comment]
I have some open questions on this one:

- [ ] We would add this to every plugin separately, right? So every repo could also configure their own templates.
- [ ] Sadly we can't really use this for links. For example replacing wiki environments would be nice. Something like:
```js
remarkPlugins: [
    [
        rehype_lodash_template,
        {
            values: {
                wiki-base-url: 'https://wiki.iota.org/shimmer/',
            },
        }
    ],
],
```
Which would allow to write text like:
```
You can find more info in this Shimmer docs [here](${wiki-base-url}some/path/in/the/shimmer/wiki)
```
But if we do that, our current broken link checker won't work as it works on the markdown AST. 
Not sure if we can somehow run the check after the remark plugins were run. Or if we just need to find a rehype plugin that checks for broken links 🤔 

Wdyt @lucas-tortora and @jlvandenhout .
But after all I think the tool is soo nice that it makes sense to merge anyway. Just something we probably need to handle in the future

**Review by lucas-tortora — APPROVED** [review]

**Comment by lucas-tortora** [comment]
> * [ ]  We would add this to every plugin separately, right? So every repo could also configure their own templates.

Can we do both? Each plugin would load the wiki templates, which could be complemented and/or overridden.

**Comment by Dr-Electron** [comment]
> Can we do both? Each plugin would load the wiki templates, which could be complemented and/or overridden.

Would be nice. But not sure what the best solution would be 🤔 
We could set env variables with the cli or something like that 🤔

**Comment by jlvandenhout** [comment]
> We would add this to every plugin separately, right?

Like it is implemented now, we need to really. We can't have a "global remark plugin", as remark plugins act on individual docs instances.

> So every repo could also configure their own templates.

This is a direct consequence of the above, not necessarily a choice.

What we could do is provide a default mapping from the core package or theme package, that we can import wherever we have a use for these templates.

An alternative is to wrap the remark plugin ourselves and provide a default mapping in the wrapping plugin. That way we can implement logic to make it work nice with the rest of the Wiki build system, like having `network` mapped to the configured `ENVIRONMENT` environment variable, or check that default mappings are not shadowed by project defined mappings, etc.

> Sadly we can't really use this for links

IMO this is not necessarily an issue. We should really take some time and figure out and document how to link properly in the Wiki. Because normally you wouldn't have to use tricks like this to properly link for example between pages under the `shimmer` subpath with relative URLs.

**Pull request merged**
