### PR TITLE
feat: add google analytics

### PR DESCRIPTION
**Pull request by marc2332**
# Description of change

Added Google Analytics. 

Live deploy: https://iota-wiki-mjwdlmc2m-mkenzo8.vercel.app/

## Links to any relevant issues

Fixes https://github.com/boxfish-studio/iota-wiki/issues/3

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by jlvandenhout** [comment]
We could also put the configuration in the root `docusaurus.config.js` [here](https://github.com/iota-wiki/iota-wiki/blob/41d949b0cc0a03f67a935e6206e42e74ff819fbb/docusaurus.config.js#L29), saves us an extra config file and having to import it in the 3 environment configs. wdyt?

**Comment by marc2332** [comment]
> We could also put the configuration in the root `docusaurus.config.js` [here](https://github.com/iota-wiki/iota-wiki/blob/41d949b0cc0a03f67a935e6206e42e74ff819fbb/docusaurus.config.js#L29), saves us an extra config file and having to import it in the 3 environment configs. wdyt?

That was actually my initial goal but I couldn't seem to get it working with this `merge function that is being used. It would definitely be a better way.

**Comment by jlvandenhout** [comment]
Ah, I see you add it to the preset config. I wanted to move away from using the preset anyway (we use less and less of it), so I'm fine adding this directly as a plugin. In this case in `docusaurus.config.js` we can add it to the production plugsin array:

```
const production = {
  ...
  plugins: [
    ...
    [
      '@docusaurus/plugin-google-gtag',
      {
        trackingID: '<tracking_id>',
        anonymizeIP: true,
      },
    ],
  ],
};
```

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
After the latest changes it doesnt seem working anymore

**Review by begonaalvarezd — APPROVED** [review]
Now works, it needs to be triggered with a `build:production` and now it appears 🙌🏼

**Pull request merged**
