### PR TITLE
Local development fix in readme for beginners

### PR DESCRIPTION
**Pull request by antonionardella**
# Description of change

Fixed README for #727 

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes issue #`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Documentation Enhancement

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have tested the wiki locally and tested that all external links work

### CODE REVIEW

**Comment by Dr-Electron** [comment]
I can't reproduce this. Can you describe the steps I need to make to reproduce it?

**Comment by antonionardella** [comment]
https://pastebin.com/dyAErMVw

**Comment by Dr-Electron** [comment]
> https://pastebin.com/HSVE566w

You need to enable core pack like it is described in the prerequisites

**Comment by antonionardella** [comment]
Layer 8 issue

**Pull request closed without merging**
