### PR TITLE
Fixes and formatting in wallet tutorial

### PR DESCRIPTION
**Pull request by adrian-grassl**
# Description of change

A few changes before this tutorial can be a proper prerequisite for further tutorials on e.g. NFT's (IPFS, Nested, Collection, ...)

## Type of change

Documentation Fix

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested the wiki locally and tested that all external links work

### CODE REVIEW

**Comment by jlvandenhout** [comment]
@Dr-Electron @lucas-tortora In the Wiki itself we converged on using two spaces instead of tabs for indentation. Prettier somehow doesn't seem to catch this in the codeblocks of this tutorial, while it should have. But do we care?

**Comment by adrian-grassl** [comment]
@jlvandenhout It looks especially off in the github preview, but not that bad in the actual wiki render. However, tab size in my local IDE is set to 4 spaces. No problem with changing this to 2, if we aligned on that for the wiki.

**Comment by jlvandenhout** [comment]
Let's keep it at 2 spaces then, to prevent a mix of tabs and spaces, and since other tutorials already seem to have converged to that standard.

**Comment by jlvandenhout** [comment]
Still not sure why Prettier doesn't catch this though, it should be able to correctly format code blocks too, according to the language used. I'll see what I can do about that.

**Review by jlvandenhout — APPROVED** [review]

**Pull request merged**
