### PR TITLE
feat: add script to watch user clicks on search page

### LINKED ISSUE #794: Search results are broken
**Describe the bug**
The search results are broken https://wiki.iota.org/search?q=native%20token
All links there return `Page Not Found`

**To Reproduce**

1. Go to https://wiki.iota.org/search?q=native%20token
2. Click on a link
3. See error

**Expected behavior**
Results should go to a working page

**Desktop (please complete the following information):**

- OS: [pop!_os]
- Browser [ chrome]

### PR DESCRIPTION
**Pull request by VmMad**
# Description of change

Add a script to watch if a user clicks on a link in the search page to avoid navigating with the SPA method.

## Links to any relevant issues

Fixes #794 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by Dr-Electron — APPROVED** [review]
LGTM. Although I have a similar problem here like with https://github.com/iota-wiki/iota-wiki/pull/934.
I'm afraid that with the "special" detection of next and shimmer if we ever update base urls or something we will forget to update this files 😅 .
Not sure if there would be a better way to share configs somehow tho 😅

**Comment by jlvandenhout** [comment]
On the other hand, I'm fine with merging this, as it allows the "initial search experience" to be inside the environment, while if the reader doesn't find what it is looking for, it can click on the "show more results" and it shows results outside the environment too, which is kind of nice I guess.

**Comment by jlvandenhout** [comment]
> LGTM. Although I have a similar problem here like with #934. I'm afraid that with the "special" detection of next and shimmer if we ever update base urls or something we will forget to update this files 😅 . Not sure if there would be a better way to share configs somehow tho 😅

And could you open an issue for this? I think this is something that is fixable.

**Comment by Dr-Electron** [comment]
I actually think the PR fixes the linked issue. But there should be another issue on how we handle different environments.
Didn't we talk about sorting them. So if you search in IOTA it would also show you Shimmer results, just not on the first page.
Maybe even with different theming. Or a dropdown in the search. I remember a lot of ideas in the room.

**Comment by Dr-Electron** [comment]
> And could you open an issue for this? I think this is something that is fixable.

Will do

**Pull request merged**
